### ISSUE TITLE
Players can't earn SP

### ISSUE THREAD

**Issue by leveljaap** [elBukkit/MagicPlugin#517]
Hello,

After encountering some bugs in earlier Magic versions I tried updating to the latest version. It is being advertised as working on 1.13 as well. Yet when I updated it, the Magic resource pack stopped working and spells couldn't be cast anymore. The commands still auto complete when I type them but when I execute them they don't work either.
`Player data request for c6554740-db67-3f70-b48f-0527f0f39df9 (leveljaap) failed, plugin not loaded yet`
Am I doing something wrong?? I just removed the old Magic plugin and then placed the new Magic plugin in the plugins folder.

EDIT: In-game it gives me "An internal error occurred while attempting to perform this command" when trying to execute a Magic command like /wand

EDIT2: When downgrading to Magic 7.7 (the latest version for 1.13) it becomes impossible to earn SP. The plugin works otherwise though. /mgive sp <amount> does still work but when casting a spell (I tried several SP-earning spells) one does not earn SP at all.

**Comment by NathanWolf** [comment]
7.7.3 was broken, sorry. I released 7.7.4 almost immediately afterward, can you please try that one?

**Comment by leveljaap** [comment]
Was 7.7.4 released for Bukkit as well? I can't see it in the File page on bukkit. (https://dev.bukkit.org/projects/magic/files)

**Comment by NathanWolf** [comment]
There is no such thing as "Bukkit" anymore. That team folded like 5 years ago and tried to take the entire community with them. 

I would definitely recommend getting builds of any of your plugins from spigotmc, since that's the only place you can legitimately get a server build anymore. I honestly want to close down my dev.bukkit.org page, but for some reason many people still go there for plugins.

I would recommend using Citizens NPCs instead of command blocks. If you really wand command blocks the /wandp command takes a player name as the first parameter.

**Comment by NathanWolf** [comment]
Oh, and yes I did release 7.7.4 to d.b.o but it is still "Under Review".

**Comment by leveljaap** [comment]
Oh okay thanks. However, players still can't earn SP in the new version. I wanted to update the plugin since it was suddenly impossible to earn SP. This might have something to do with the configuration, as players were able to earn SP before. The only thing I changed in the config was add some new wands and paths in the right config files.

About the wandp, I need to work with selectors, not playernames. Is this possible in any way?

**Comment by NathanWolf** [comment]
`/mgive @p thewand` would be the best way. 

I don't know of anything wrong with SP in the plugin, so it may be a config issue. Assuming they're not just on SP cooldown... ?

**Comment by leveljaap** [comment]
`/mgive @p thewand` gives me `Error parsing count: wand, should be an integer.`
`/wandp @p` gives me `Can't find player @p`

As of the SP, after editing the config, none of the wands gave SP anymore, even casting with /cast doesn't give SP. The only thing I did was add a few wands, I didn't change anything about the existing wands.

**Comment by NathanWolf** [comment]
Selectors are a vanilla/spigot thing, so if that's not working I can't do much about it, sorry.

Casting with /cast doesn't earn SP, it's not meant for gameplay.

Your'e aware of the 15-minute SP cooldown, right?

**Comment by leveljaap** [comment]
15 minutes? I remember being able to earn SP every time I cast something... I was certainly not aware of a cooldown this long. That might be the problem after all, however, why would you have a cooldown that long? Makes it nearly impossible to get new spells

**Comment by NathanWolf** [comment]
You do not earn SP with every cast. Lower levels of Magic Missile have a shorter cooldown to get players started, but all other spells take 15 minutes to earn *full* SP. You may earn partial amounts with casts before then.

Progression is aimed at a few weeks of casual playing to max out a wand, maybe more. The cooldown discourages grinding, without it someone could easily max out in a day. This is not fun for other players (if it's PvP) and makes the maxed out player get bored quickly, too.

It's up to you of course. If you want to quickly test if that's the problem you can `/mage reset` yourself and see if you earn SP right away. If that doesn't work there could be something else wrong.

To change the cooldown you would add something like this to plugins/Magic/spells.yml

```
default:
    # Spells take 15 minutes to return to full SP earning potential
    earns_cooldown: 900000
```

It's in milliseconds so it'll take some math ;)

All spells except Magic Missile (levels 1-3) use that value.

Per:
https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/resources/defaults/spells/default.yml

**Comment by leveljaap** [comment]
Hmm then there's definitely something wrong... I tried with a completely blank account with a new wand and just continuously casted Magic Missile yet I didn't earn any SP. I'll upload the configs to show what I've changed, although I'm not sure the config is the problem.

**Comment by NathanWolf** [comment]
Were you hitting a mob with the spell?

**Comment by leveljaap** [comment]
Oh my god I'm sorry. I completely forgot the spell had to hit. My bad.

**Comment by NathanWolf** [comment]
😂 No worries, that's why I try to cover all the bases! Let me know if it's still seeming broken.

**Comment by leveljaap** [comment]
Thank you so much for all your help and I'm sorry for the trouble...
